name: Build and publish image to Docker Hub

on: push

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build ./ -t mehmetemin123456789/spring-data-jpa:latest
      - name: push image to docker hub
        run: | 
         docker push mehmetemin123456789/spring-data-jpa:latest


