name: Test Workflow 2

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Print message
        run: echo "Workflow çalıştı! ve Swagger güncellendi."


