#name: Build and publish image to Docker Hub
#
#on: push
#
#jobs:
#  publish_images:
#    runs-on: ubuntu-latest
#    steps:
#      - name: checkout
#        uses: actions/checkout@v4
#      - name: Build with Maven
#        run: mvn clean package -DskipTests
#      - name: build image
#        run:  docker build ./ -t mehmetemin123456789/spring-data-jpa:latest
#      - name: push image to docker hub
#        run: |
#         docker login -u mehmetemin123456789 -p ${{secrets.DOCKER_HUB_TOKEN}}
#         docker push mehmetemin123456789/spring-data-jpa:latest


name: Build and publish image to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Run Checkstyle (Google)
        run: mvn -B clean checkstyle:check
        

  docker:
    runs-on: ubuntu-latest
    needs: quality
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/spring-data-jpa:latest .

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/spring-data-jpa:latest
